### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by FredOloton** [lyokha/nginx-combined-upstreams-module#2]

**Comment by FredOloton** [comment]
Hi the module looks great from reading the docs, but it is not clear if I am supposed to build this separately or recompile nginx from source with it. I have no idea how to add this to my project. I've already pulled and there does not seem to be a makerfile or anything else that indicates a conventional build process. I might helpful for people that come across this great concept of a module to steps to adding to nginx or at least a reference to another place that does. Granted I am not a C developer.

**Comment by lyokha** [comment]
Hi. Thanks for your assessment. The build is standard for Nginx. You can build it statically with the whole Nginx code or dynamically, in a separate shared library. In both cases you need source code of Nginx. The Nginx' `configure/Makefile` look up file `config` in the directory of the module and load it at the build time. 

1. Static linkage (in the directory of Nginx' sources)

  ```ShellSession
  ./configure --add-module=/path/to/this/module/directory
  make
  # optionally
  make install
  ```

2. Dynamic library (in the directory of Nginx' sources)

  ```ShellSession
  ./configure --add-dynamic-module=/path/to/this/module/directory
  make
  # or
  make modules
  # optionally
  make install
  ```

If you build the module as a dynamic library, you'll need to add the load directive in Nginx configuration:

```nginx
load_module modules/ngx_http_combined_upstreams_module.so
```

(use absolute path to the built library if you didn't `make install`). You can also find how it gets built in the github action in .github/workflows/ci.yml. There it gets built as a static module.

I'll add these instructions in README soon.

**Comment by FredOloton** [comment]
Thank you so much for your quick response. I will use the method you suggested. You seem to be a great maintainer and I appreciate you covering this use case.

**Comment by FredOloton** [comment]
Also small side note before closing this issue, can you give me a range of compatibility with nginx versions or is it compatible with all versions?

**Comment by lyokha** [comment]
https://github.com/lyokha/nginx-combined-upstreams-module/actions/runs/7602708792 - here is the compatibility list: from Nginx 1.16 to head snapshot, it should also work with earlier versions.
